name: ios_f_n_fantastictimetodecide_3286
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  logger: ^2.5.0
  flutter_bloc: ^9.0.0
  just_audio: ^0.9.46
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  flutter_fortune_wheel: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/onboarding_images/
